# Generated by Django 4.2.18 on 2025-02-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('trivias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='users',
            field=models.ManyToManyField(to='users.user'),
        ),
    ]
